#!/usr/bin/python

from __future__ import print_function
import sys

from utils.downstream_branches import get_downstream_branches
from utils.pick_item import pick_item


def main():
  downstream_branches = get_downstream_branches()
  if len(downstream_branches) == 0:
    print('No downstream branches.', file=sys.stderr)
  elif len(downstream_branches) == 1:
    print(downstream_branches[0])
  else:
    print(pick_item(downstream_branches, 'Select downstream branch', file=sys.stderr))


if __name__ == '__main__':
  main()
