#!/usr/bin/python3

# Interactive script for renaming git branches to start with '_' to mark them as being uploaded to Rietveld.

import re
import subprocess


def main():
  m = re.match(r'On branch (.+)', subprocess.check_output(['git', 'status']).decode('utf-8'))
  if not m:
    print('Not currently on any branch.')
    return
  branch = m.group(1)
  if branch[0] != '+':
    print('Branch', branch, 'not renamed.')
    return
  new_branch = '_' + branch[1:]
  subprocess.check_call(['git', 'branch', '-m', branch, new_branch])
  print('Branch', branch, 'renamed as:', new_branch)

if __name__ == '__main__':
  main()
