#!/bin/sh
BRANCH=$(git current-branch)
UPSTREAM=$(git upstream-branch)
BASE=$(git merge-base $BRANCH $UPSTREAM)
DIFF=$(git diff $BASE $BRANCH)
OLD_COMMIT=$(git log -1 --pretty=%H)
git reset --hard $UPSTREAM
COMMIT_MESSAGE="Squash rebased $BRANCH onto $UPSTREAM.

Previous commit position at: $OLD_COMMIT"
if echo "$DIFF" | git apply -3; then
  git add -A
  git commit -m "$COMMIT_MESSAGE"
  git log --color=auto -1
else
  echo "COMMIT_MESSAGE=$COMMIT_MESSAGE"
  echo "Squash rebase failed!"
  echo "Resolve conflicts and commit with the above commit message"
fi
